name: Build Flutter App on Android and iOS

on:
  push:
    branches-ignore:
    - master
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'

    - name: Cache pub dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.FLUTTER_HOME }}/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Flutter upgrade
      run: flutter upgrade
    - name: Download dependencies
      run: flutter pub get
    - name: Flutter test
      run: flutter test
    - name: Build android
      run: flutter build apk
    - name: Clean up
      run: |
        mv ./build/app/outputs/flutter-apk/app-release.apk android-release.apk
        flutter clean
    - name: Build iOS
      run: flutter build ios --no-codesign
    - name: Clean up
      run: |
        mkdir -p Payload
        mv ./build/ios/iphoneos/Runner.app Payload
        zip -r -y Payload.zip Payload/Runner.app
        mv Payload.zip ios-release.ipa
        rm -Rf Payload
        flutter clean
        
    - uses: actions/upload-artifact@v2
      with:
        name: flutter-build
        path: |
          android-release.apk
          ios-release.ipa